name: nfl-predictor
channels:
  - conda-forge
  - defaults
dependencies:
  - aws-c-auth=0.9.3=h2970c50_0
  - aws-c-cal=0.9.13=h46f3b43_1
  - aws-c-common=0.12.6=hfd05255_0
  - aws-c-compression=0.3.1=hcb3a2da_9
  - aws-c-event-stream=0.5.7=ha388e84_1
  - aws-c-http=0.10.7=hc678f4a_5
  - aws-c-io=0.23.3=h0d5b9f9_5
  - aws-c-mqtt=0.13.3=hfa314fa_11
  - aws-c-s3=0.11.3=ha659bf3_1
  - aws-c-sdkutils=0.2.4=hcb3a2da_4
  - aws-checksums=0.2.7=hcb3a2da_5
  - aws-crt-cpp=0.35.4=hca034e6_0
  - aws-sdk-cpp=1.11.606=hac16450_10
  - bzip2=1.0.8=h2bbff1b_6
  - c-ares=1.34.6=hfd05255_0
  - ca-certificates=2026.1.4=h4c7d964_0
  - expat=2.7.3=h885b0b7_4
  - joblib=1.5.3=pyhd8ed1ab_0
  - krb5=1.21.3=hdf4eb48_0
  - libabseil=20250512.1=cxx17_habfad5f_0
  - libarrow=22.0.0=h5f2f476_6_cuda
  - libarrow-acero=22.0.0=h7d8d6a5_6_cuda
  - libarrow-compute=22.0.0=h2db994a_6_cuda
  - libarrow-dataset=22.0.0=h7d8d6a5_6_cuda
  - libarrow-substrait=22.0.0=hf865cc0_6_cuda
  - libblas=3.11.0=5_hf2e6a31_mkl
  - libbrotlicommon=1.2.0=hfd05255_1
  - libbrotlidec=1.2.0=hfd05255_1
  - libbrotlienc=1.2.0=hfd05255_1
  - libcblas=3.11.0=5_h2a3cdd5_mkl
  - libcrc32c=1.1.2=h0e60522_0
  - libcurl=8.18.0=h43ecb02_0
  - libevent=2.1.12=h3671451_1
  - libexpat=2.7.3=h885b0b7_4
  - libffi=3.4.4=hd77b12b_1
  - libgoogle-cloud=2.39.0=h19ee442_0
  - libgoogle-cloud-storage=2.39.0=he04ea4c_0
  - libgrpc=1.73.1=h317e13b_1
  - libhwloc=2.12.1=default_h88281d1_1000
  - libiconv=1.18=hc1393d2_2
  - liblapack=3.11.0=5_hf9ab0e9_mkl
  - libparquet=22.0.0=h7051d1f_6_cuda
  - libprotobuf=6.31.1=hdcda5b4_4
  - libre2-11=2025.11.05=h0eb2380_0
  - libssh2=1.11.1=h9aa295b_0
  - libthrift=0.22.0=h23985f6_1
  - libutf8proc=2.11.2=hb980946_0
  - libwinpthread=12.0.0.r4.gg4f2fc60ca=h57928b3_10
  - libxml2=2.13.9=h741aa76_0
  - libzlib=1.3.1=h02ab6af_0
  - llvm-openmp=21.1.8=h4fa8253_0
  - lz4-c=1.10.0=h2466b09_1
  - mkl=2025.3.0=hac47afa_455
  - numpy=1.26.4=py310hf667824_0
  - openssl=3.6.0=h725018a_0
  - orc=2.2.1=h7414dfc_0
  - pandas=2.3.3=py310hed136d8_2
  - pip=25.3=pyhc872135_0
  - py4j=0.10.9.7=pyhd8ed1ab_0
  - pyarrow=22.0.0=py310h5588dad_0
  - pyarrow-core=22.0.0=py310h54c75c4_0_cuda
  - pyspark=3.5.1=pyhd8ed1ab_0
  - python=3.10.19=h981015d_0
  - python-dateutil=2.9.0.post0=pyhe01879c_2
  - python-tzdata=2025.3=pyhd8ed1ab_0
  - python_abi=3.10=2_cp310
  - pytz=2025.2=pyhd8ed1ab_0
  - re2=2025.11.05=ha104f34_0
  - scikit-learn=1.7.2=py310h21054b0_0
  - scipy=1.15.2=py310h15c175c_0
  - setuptools=80.9.0=py310haa95532_0
  - six=1.17.0=pyhe01879c_1
  - snappy=1.2.2=h7fa0ca8_1
  - sqlite=3.51.1=hda9a48d_0
  - tbb=2022.3.0=hd094cb3_1
  - threadpoolctl=3.6.0=pyhecae5ae_0
  - tk=8.6.15=hf199647_0
  - tzdata=2025b=h04d1e81_0
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wheel=0.45.1=py310haa95532_0
  - xz=5.6.4=h4754444_1
  - zlib=1.3.1=h02ab6af_0
  - zstd=1.5.7=h534d264_6
  - pip:
      - altair==6.0.0
      - attrs==25.4.0
      - blinker==1.9.0
      - cachetools==6.2.4
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - colorama==0.4.6
      - contourpy==1.3.2
      - cycler==0.12.1
      - fonttools==4.61.1
      - gitdb==4.0.12
      - gitpython==3.1.46
      - idna==3.11
      - jinja2==3.1.6
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - kiwisolver==1.4.9
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - narwhals==2.15.0
      - packaging==25.0
      - pillow==12.1.0
      - plotly==6.5.2
      - protobuf==6.33.4
      - pydeck==0.9.1
      - pyparsing==3.3.1
      - python-dotenv==1.2.1
      - pyyaml==6.0.3
      - referencing==0.37.0
      - requests==2.32.5
      - rpds-py==0.30.0
      - seaborn==0.13.2
      - smmap==5.0.2
      - streamlit==1.53.0
      - tenacity==9.1.2
      - toml==0.10.2
      - tornado==6.5.4
      - typing-extensions==4.15.0
      - urllib3==2.6.3
      - watchdog==6.0.0
      - xgboost==3.1.3
prefix: C:\Users\PC\anaconda3\envs\nfl-predictor
